---
docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_apt_key_path: /etc/apt/keyrings/docker.asc
docker_apt_source_path: /etc/apt/sources.list.d/docker.sources

docker_architecture_map:
  x86_64: amd64
  aarch64: arm64

docker_conflicting_packages:
  - docker.io
  - docker-compose
  - docker-compose-v2
  - docker-doc
  - podman-docker
  - containerd
  - runc

docker_enable_hello_world_test: true
